### ISSUE TITLE
 Starting with Ember 2.1 providing two arguments to an initializer will trigger a deprecation

### ISSUE THREAD

**Issue by Artmann** [kategengler/ember-feature-flags#37]
Ember-feature flags throws a deprecation in Ember 2.2.0

```
DEPRECATION: The `initialize` method for Application initializer 'ember-feature-flags' should take only one argument - `App`, an instance of an `Application`. [deprecation id: ember-application.app-initializer-initialize-arguments] See http://emberjs.com/deprecations/v2.x/#toc_initializer-arity for more details.
        at HANDLERS.(anonymous function) (http://localhost:8014/assets/vendor.js:15190:7)
        at raiseOnDeprecation (http://localhost:8014/assets/vendor.js:15100:12)
        at HANDLERS.(anonymous function) (http://localhost:8014/assets/vendor.js:15190:7)
        at invoke (http://localhost:8014/assets/vendor.js:15206:7)
        at deprecate (http://localhost:8014/assets/vendor.js:15159:32)
        at Object.deprecate (http://localhost:8014/assets/vendor.js:25055:37)
        at http://localhost:8014/assets/vendor.js:13870:28
        at http://localhost:8014/assets/vendor.js:13907:9
        at Object.visit [as default] (http://localhost:8014/assets/vendor.js:64205:5)
```

**Comment by oliverwilkie** [comment]
This fork fixes that
https://github.com/Arkham/ember-feature-flags/commit/a5a7facdc9d60a8922156ffb20bdb67644bf98fa

**Comment by acorncom** [comment]
Fixed by https://github.com/kategengler/ember-feature-flags/pull/32
